version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: PostgresSql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jottas_burguer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jottas_burguer_network

volumes:
  postgres_data:

networks:
  jottas_burguer_network:
    driver: bridge